---

- when: matrix_synapse_enabled | bool
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/inject_into_nginx_proxy.yml"
  tags:
    - setup-all
    - setup-synapse
    - start
    - start-all
    - start-group
    - restart
    - restart-all
    - restart-group
    - stop
    - stop-all
    - stop-group

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/validate_config.yml"
  when: run_setup | bool and matrix_synapse_enabled | bool
  tags:
    - setup-all
    - setup-synapse

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/setup_synapse.yml"
  when: run_setup | bool
  tags:
    - setup-all
    - setup-synapse

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/import_media_store.yml"
  when: run_synapse_import_media_store | bool
  tags:
    - import-synapse-media-store

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/register_user.yml"
  when: run_synapse_register_user | bool and matrix_synapse_enabled | bool
  tags:
    - register-user

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/self_check_client_api.yml"
  delegate_to: 127.0.0.1
  become: false
  when: run_self_check | bool
  tags:
    - self-check

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/self_check_federation_api.yml"
  delegate_to: 127.0.0.1
  become: false
  when: run_self_check | bool
  tags:
    - self-check

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/update_user_password.yml"
  when: run_synapse_update_user_password | bool and matrix_synapse_enabled | bool
  tags:
    - update-user-password

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/rust-synapse-compress-state/main.yml"
  when: run_synapse_rust_synapse_compress_state | bool
  tags:
    - rust-synapse-compress-state

- name: Mark matrix-synapse role as executed
  ansible.builtin.set_fact:
    matrix_synapse_role_executed: true
  tags:
    - always
