---

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/init.yml"
  tags:
    - always

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/validate_config.yml"
  when: "run_setup | bool and matrix_matrix_ldap_registration_proxy_enabled | bool"
  tags:
    - setup-all
    - setup-matrix-ldap-registration-proxy

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/setup_install.yml"
  when: "run_setup | bool and matrix_matrix_ldap_registration_proxy_enabled | bool"
  tags:
    - setup-all
    - setup-matrix-ldap-registration-proxy

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/setup_uninstall.yml"
  when: "run_setup | bool and not matrix_matrix_ldap_registration_proxy_enabled | bool"
  tags:
    - setup-all
    - setup-matrix-ldap-registration-proxy

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/self_check_matrix_ldap_registration_proxy.yml"
  delegate_to: 127.0.0.1
  become: false
  when: "run_self_check | bool and matrix_matrix_ldap_registration_proxy_enabled | bool"
  tags:
    - self-check
