---

- ansible.builtin.set_fact:
    matrix_ldap_registration_proxy_url_endpoint_public: "https://{{ matrix_server_fqn_matrix }}/_matrix/client/r0/register"

- name: Check matrix_ldap_registration_proxy Service
  ansible.builtin.uri:
    url: "{{ matrix_ldap_registration_proxy_url_endpoint_public }}"
    follow_redirects: none
    validate_certs: "{{ matrix_matrix_ldap_registration_proxy_self_check_validate_certificates }}"
  check_mode: false
  register: result_matrix_ldap_registration_proxy
  ignore_errors: true

- name: Fail if matrix_ldap_registration_proxy Service not working
  ansible.builtin.fail:
    msg: "Failed checking matrix_ldap_registration_proxy is up at `{{ matrix_server_fqn_matrix }}` (checked endpoint: `{{ matrix_ldap_registration_proxy_url_endpoint_public }}`). Is matrix_ldap_registration_proxy running? Is port 443 open in your firewall? Full error: {{ result_matrix_ldap_registration_proxy }}"
  when: "result_matrix_ldap_registration_proxy.failed or 'json' not in result_matrix_ldap_registration_proxy"

- name: Report working matrix_ldap_registration_proxy Service
  ansible.builtin.debug:
    msg: "matrix_ldap_registration_proxy at `{{ matrix_server_fqn_matrix }}` is working (checked endpoint: `{{ matrix_ldap_registration_proxy_url_endpoint_public }}`)"
