---

- name: Fail if required riot-web settings not defined
  fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`) for using riot-web.
  when: "vars[item] == ''"
  with_items:
    - "matrix_riot_web_default_hs_url"
