---

- name: Ensure matrix-reminder-bot paths exist
  file:
    path: "{{ item.path }}"
    state: directory
    mode: 0750
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"
  with_items:
    - { path: "{{ matrix_bot_matrix_reminder_bot_config_path }}", when: true }
    - { path: "{{ matrix_bot_matrix_reminder_bot_data_path }}", when: true }
    - { path: "{{ matrix_bot_matrix_reminder_bot_data_store_path }}", when: true }
  when: "item.when|bool"

- name: Ensure matrix-reminder-bot image is pulled
  docker_image:
    name: "{{ matrix_bot_matrix_reminder_bot_docker_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ matrix_bot_matrix_reminder_bot_docker_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else matrix_bot_matrix_reminder_bot_docker_image_force_pull }}"

- name: Ensure matrix-reminder-bot config installed
  copy:
    content: "{{ matrix_bot_matrix_reminder_bot_configuration|to_nice_yaml }}"
    dest: "{{ matrix_bot_matrix_reminder_bot_config_path }}/config.yaml"
    mode: 0644
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"

- name: Ensure matrix-bot-matrix-reminder-bot.service installed
  template:
    src: "{{ role_path }}/templates/systemd/matrix-bot-matrix-reminder-bot.service.j2"
    dest: "{{ matrix_systemd_path }}/matrix-bot-matrix-reminder-bot.service"
    mode: 0644
  register: matrix_bot_matrix_reminder_bot_systemd_service_result

- name: Ensure systemd reloaded after matrix-bot-matrix-reminder-bot.service installation
  service:
    daemon_reload: yes
  when: "matrix_bot_matrix_reminder_bot_systemd_service_result.changed|bool"
