---
- name: "Set up a Matrix server"
  hosts: "{{ target if target is defined else 'matrix_servers' }}"
  become: true

  roles:
    - matrix-base
    - matrix-mailer
    - matrix-postgres
    - matrix-corporal
    - matrix-bridge-appservice-discord
    - matrix-bridge-appservice-slack
    - matrix-bridge-appservice-irc
    - matrix-bridge-mautrix-facebook
    - matrix-bridge-mautrix-telegram
    - matrix-bridge-mautrix-whatsapp
    - matrix-synapse
    - matrix-riot-web
    - matrix-mxisd
    - matrix-dimension
    - matrix-nginx-proxy
    - matrix-coturn
    - matrix-common-after
