---

- name: Gather package facts
  package_facts:

- set_fact:
    run_docker_installation: "{{ matrix_docker_installation_enabled|bool and 'docker.io' not in ansible_facts.packages }}"

- include_tasks: "{{ role_path }}/tasks/server_base/setup_centos.yml"
  when: ansible_distribution == 'CentOS'

- include_tasks: "{{ role_path }}/tasks/server_base/setup_debian.yml"
  when: ansible_os_family == 'Debian'

- name: Ensure Docker is started and autoruns
  service:
    name: docker
    state: started
    enabled: yes

- name: Ensure ntpd is started and autoruns
  service:
    name: "{{ 'ntpd' if ansible_os_family == 'RedHat' else 'ntp' }}"
    state: started
    enabled: yes
