---

- name: Ensure Docker repository is enabled
  template:
    src: "{{ role_path }}/files/yum.repos.d/{{ item }}"
    dest: "/etc/yum.repos.d/{{ item }}"
    owner: "root"
    group: "root"
    mode: 0644
  with_items:
    - docker-ce.repo

- name: Ensure Docker's RPM key is trusted
  rpm_key:
    state: present
    key: https://download.docker.com/linux/centos/gpg

- name: Ensure yum packages are installed
  yum:
    name:
      - bash-completion
      - docker-python
      - ntp
      - fuse
    state: latest
    update_cache: yes

- name: Ensure docker-ce is installed
  yum:
    name:
      - docker-ce
    state: latest
    update_cache: yes
