---

- name: Fail if no database is configured for Etherpad
  ansible.builtin.fail:
    msg: >-
      Etherpad requires a dedicated Postgres database. Please enable the built in one, or configure an external DB by redefining "matrix_etherpad_database_hostname"
  when: matrix_etherpad_database_hostname == "matrix-postgres" and not matrix_postgres_enabled
