# A bridge between Matrix and multiple project management services, such as GitHub, GitLab and JIRA.
# https://github.com/Half-Shot/matrix-hookshot

matrix_hookshot_enabled: true

matrix_hookshot_version: 1.0.0
matrix_hookshot_docker_image: "{{ matrix_container_global_registry_prefix }}halfshot/hookshot:{{ matrix_hookshot_version }}"
matrix_hookshot_docker_image_force_pull: "{{ matrix_hookshot_docker_image.endswith(':latest') }}"

matrix_hookshot_base_path: "{{ matrix_base_data_path }}/hookshot"

matrix_hookshot_homeserver_address: "{{ matrix_homeserver_container_url }}"

matrix_hookshot_public_endpoint: /hookshot

# metrics work only in conjunction with matrix_synapse_metrics_enabled etc
matrix_hookshot_metrics_enabled: true
matrix_hookshot_metrics_port: 9001

matrix_hookshot_hookshot_port: 9993
matrix_hookshot_webhook_port: 9000

# you need to create a GitHub app to enable this
# https://half-shot.github.io/matrix-hookshot/setup/github.html
matrix_hookshot_github_enabled: true
matrix_hookshot_github_appid: 123
matrix_hookshot_github_private_key: ''
matrix_hookshot_github_secret: '' # "Webhook secret" on the GitHub App page
matrix_hookshot_github_oauth_enabled: true
matrix_hookshot_github_oauth_id: '' # "Client ID" on the GitHub App page
matrix_hookshot_github_oauth_secret: '' # "Client Secret" on the GitHub App page
matrix_hookshot_github_oauth_endpoint: "{{ matrix_hookshot_public_endpoint }}/oauth"
matrix_hookshot_github_oauth_uri: "{{ matrix_server_fqn_matrix }}{{ matrix_hookshot_github_oauth_endpoint }}"
matrix_hookshot_github_ignore_hooks: '{}'
matrix_hookshot_github_command_prefix: '!gh'
matrix_hookshot_github_show_issue_room_link: false
matrix_hookshot_github_pr_diff: '{enabled: false, maxLines: 5}'
matrix_hookshot_github_including_labels: ''
matrix_hookshot_github_excluding_labels: ''

matrix_hookshot_gitlab_enabled: true
matrix_hookshot_gitlab_instances:
  gitlab.com:
    url: https://gitlab.com

matrix_hookshot_gitlab_secret: ''

matrix_hookshot_jira_enabled: true
matrix_hookshot_jira_secret: ''
matrix_hookshot_jira_oauth_id: ''
matrix_hookshot_jira_oauth_secret: ''
matrix_hookshot_jira_oauth_endpoint: "{{ matrix_hookshot_public_endpoint }}/jira/oauth"
matrix_hookshot_jira_oauth_uri: "{{ matrix_server_fqn_matrix }}{{ matrix_hookshot_jira_oauth_endpoint }}"

matrix_hookshot_generic_enabled: true
matrix_hookshot_generic_endpoint: '{{ matrix_hookshot_public_endpoint }}/webhooks'
matrix_hookshot_generic_urlprefix: '{{ matrix_server_fqn_matrix }}{{ matrix_hookshot_generic_endpoint }}'
matrix_hookshot_generic_allow_js_transformation_functions: false
matrix_hookshot_generic_user_id_prefix: 'webhooks_'

# matrix_hookshot_provisioning_port: 9002
matrix_hookshot_provisioning_secret: ''

# A list of extra arguments to pass to the container
matrix_hookshot_container_extra_arguments: []

# List of systemd services that service depends on.
matrix_hookshot_systemd_required_services_list: ['docker.service']

# List of systemd services that service wants
matrix_hookshot_systemd_wanted_services_list: []

matrix_hookshot_appservice_token: ''
matrix_hookshot_homeserver_token: ''

# Default configuration template which covers the generic use case.
# You can customize it by controlling the various variables inside it.
#
# For a more advanced customization, you can extend the default (see `matrixhookshot_configuration_extension_yaml`)
# or completely replace this variable with your own template.
matrix_hookshot_configuration_yaml: "{{ lookup('template', 'templates/config.yml.j2') }}"

matrix_hookshot_configuration_extension_yaml: |
  # Your custom YAML configuration goes here.
  # This configuration extends the default starting configuration (`matrix_hookshot_configuration_yaml`).
  #
  # You can override individual variables from the default configuration, or introduce new ones.
  #
  # If you need something more special, you can take full control by
  # completely redefining `matrix_hookshot_configuration_yaml`.

matrix_hookshot_configuration_extension: "{{ matrix_hookshot_configuration_extension_yaml|from_yaml if matrix_hookshot_configuration_extension_yaml|from_yaml is mapping else {} }}"

# Holds the final configuration (a combination of the default and its extension).
# You most likely don't need to touch this variable. Instead, see `matrix_hookshot_configuration_yaml`.
matrix_hookshot_configuration: "{{ matrix_hookshot_configuration_yaml|from_yaml|combine(matrix_hookshot_configuration_extension, recursive=True) }}"

# Default registration template which covers the generic use case.
# You can customize it by controlling the various variables inside it.
#
# For a more advanced customization, you can extend the default (see `matrixhookshot_registration_extension_yaml`)
# or completely replace this variable with your own template.
matrix_hookshot_registration_yaml: "{{ lookup('template', 'templates/registration.yml.j2') }}"

matrix_hookshot_registration_extension_yaml: |
  # Your custom YAML registration goes here.
  # This registration extends the default starting registration (`matrix_hookshot_registration_yaml`).
  #
  # You can override individual variables from the default registration, or introduce new ones.
  #
  # If you need something more special, you can take full control by
  # completely redefining `matrix_hookshot_registration_yaml`.

matrix_hookshot_registration_extension: "{{ matrix_hookshot_registration_extension_yaml|from_yaml if matrix_hookshot_registration_extension_yaml|from_yaml is mapping else {} }}"

# Holds the final registration (a combination of the default and its extension).
# You most likely don't need to touch this variable. Instead, see `matrix_hookshot_registration_yaml`.
matrix_hookshot_registration: "{{ matrix_hookshot_registration_yaml|from_yaml|combine(matrix_hookshot_registration_extension, recursive=True) }}"
