---

- import_tasks: tasks/self_check/self_check_dns.yml

- import_tasks: tasks/self_check/self_check_client_api.yml

- import_tasks: tasks/self_check/self_check_federation_api.yml

- import_tasks: tasks/self_check/self_check_riot_web.yml
  when: "matrix_riot_web_enabled"

- import_tasks: tasks/self_check/self_check_mxisd.yml
  when: "matrix_mxisd_enabled"

- import_tasks: tasks/self_check/self_check_well_known.yml

- import_tasks: tasks/self_check/self_check_corporal.yml
  when: "matrix_corporal_enabled"