---

- name: Ensure Mautrix Facebook image is pulled
  docker_image:
    name: "{{ matrix_mautrix_facebook_docker_image }}"
  when: "matrix_mautrix_facebook_enabled"

- name: Ensure Mautrix Facebook configuration path exists
  file:
    path: "{{ matrix_mautrix_facebook_base_path }}"
    state: directory
    mode: 0750
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_username }}"
  when: "matrix_mautrix_facebook_enabled"

- name: Check if a mautrix-facebook configuration file exists
  stat:
    path: "{{ matrix_mautrix_facebook_base_path }}/config.yaml"
  register: mautrix_facebook_config_file_stat
  when: "matrix_mautrix_facebook_enabled"

- name: Ensure Matrix Mautrix facebook config installed
  template:
    src: "{{ role_path }}/templates/ext/mautrix-facebook/config.yaml.j2"
    dest: "{{ matrix_mautrix_facebook_base_path }}/config.yaml"
    mode: 0644
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_username }}"
  when: "matrix_mautrix_facebook_enabled and not mautrix_facebook_config_file_stat.stat.exists"

- name: (Migration) Fix up old configuration
  lineinfile:
    path: "{{ matrix_mautrix_facebook_base_path }}/config.yaml"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  with_items:
    - {'regexp': '^(\s+)filename: \./mautrix-facebook.log', 'line': '\1filename: /data/mautrix-facebook.log'}
    - {'regexp': '^(\s+)database:', 'line': '\1database: sqlite:////data/mautrix-facebook.db'}
  when: "matrix_mautrix_facebook_enabled and mautrix_facebook_config_file_stat.stat.exists"

- name: Ensure matrix-mautrix-facebook.service installed
  template:
    src: "{{ role_path }}/templates/ext/mautrix-facebook/systemd/matrix-mautrix-facebook.service.j2"
    dest: "/etc/systemd/system/matrix-mautrix-facebook.service"
    mode: 0644
  register: matrix_mautrix_facebook_systemd_service_result
  when: "matrix_mautrix_facebook_enabled"

- name: Ensure systemd reloaded after matrix-mautrix-facebook.service installation
  service:
    daemon_reload: yes
  when: "matrix_mautrix_facebook_enabled and matrix_mautrix_facebook_systemd_service_result.changed"

- name: Check if a mautrix-facebook registration file exists
  stat:
    path: "{{ matrix_mautrix_facebook_base_path }}/registration.yaml"
  register: mautrix_facebook_registration_file_stat
  when: "matrix_mautrix_facebook_enabled"

- name: Generate matrix-mautrix-facebook registration.yaml if it doesn't exist
  shell:
    cmd: >-
      /usr/bin/docker run
      --rm
      --user={{ matrix_user_uid }}:{{ matrix_user_gid }}
      --cap-drop=ALL
      --name matrix-mautrix-facebook-gen
      -v {{ matrix_mautrix_facebook_base_path }}:/data:z
      {{ matrix_mautrix_facebook_docker_image }}
      python3 -m mautrix_facebook -g -c /data/config.yaml -r /data/registration.yaml
  when: "matrix_mautrix_facebook_enabled and not mautrix_facebook_registration_file_stat.stat.exists"

- set_fact:
    matrix_synapse_app_service_config_file_mautrix_facebook: '/app-registration/mautrix-facebook.yml'
  when: "matrix_mautrix_facebook_enabled"

- set_fact:
    matrix_synapse_container_additional_volumes: >
      {{ matrix_synapse_container_additional_volumes }}
      +
      {{ [{'src': '{{ matrix_mautrix_facebook_base_path }}/registration.yaml', 'dst': '{{ matrix_synapse_app_service_config_file_mautrix_facebook }}', 'options': 'ro'}] }}
  when: "matrix_mautrix_facebook_enabled"

- set_fact:
    matrix_synapse_app_service_config_files: >
      {{ matrix_synapse_app_service_config_files }}
      +
      {{ ["{{ matrix_synapse_app_service_config_file_mautrix_facebook }}"] | to_nice_json  }}
  when: "matrix_mautrix_facebook_enabled"

#
# Tasks related to getting rid of matrix-mautrix-facebook (if it was previously enabled)
#

- name: Ensure matrix-mautrix-facebook.service doesn't exist
  file:
    path: "/etc/systemd/system/matrix-mautrix-facebook.service"
    state: absent
  when: "not matrix_mautrix_facebook_enabled"
