- import_tasks: "{{ role_path }}/tasks/init.yml"
  tags:
    - always

- import_tasks: "{{ role_path }}/tasks/validate_config.yml"
  when: "run_setup and matrix_appservice_discord_enabled"
  tags:
    - setup-all
    - setup-appservice-discord

- import_tasks: "{{ role_path }}/tasks/setup-install.yml"
  when: "run_setup and matrix_appservice_discord_enabled"
  tags:
    - setup-all
    - setup-appservice-discord

- import_tasks: "{{ role_path }}/tasks/setup-uninstall.yml"
  when: "run_setup and not matrix_appservice_discord_enabled"
  tags:
    - setup-all
    - setup-appservice-discord
