---

- name: Ensure Email2Matrix paths exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"
  with_items:
    - "{{ matrix_email2matrix_base_path }}"
    - "{{ matrix_email2matrix_config_dir_path }}"

- name: Ensure Email2Matrix configuration file created
  template:
    src: "{{ role_path }}/templates/config.json.j2"
    dest: "{{ matrix_email2matrix_config_dir_path }}/config.json"
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"
    mode: 0640

- name: Ensure Email2Matrix image is pulled
  docker_image:
    name: "{{ matrix_email2matrix_docker_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ matrix_email2matrix_docker_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else matrix_email2matrix_docker_image_force_pull }}"

- name: Ensure matrix-email2matrix.service installed
  template:
    src: "{{ role_path }}/templates/systemd/matrix-email2matrix.service.j2"
    dest: "{{ matrix_systemd_path }}/matrix-email2matrix.service"
    mode: 0644
  register: matrix_email2matrix_systemd_service_result

- name: Ensure systemd reloaded after matrix-email2matrix.service installation
  service:
    daemon_reload: yes
  when: "matrix_email2matrix_systemd_service_result.changed|bool"
