---

- name: Determine well-known files to check (Matrix)
  set_fact:
    well_known_file_checks:
      - path: /.well-known/matrix/client
        purpose: Client Discovery
        cors: true
        follow_redirects: false

- block:
    - set_fact:
        well_known_file_check_matrix_server:
          path: /.well-known/matrix/server
          purpose: Server Discovery
          cors: false
          follow_redirects: true

    - name: Determine domains that we require certificates for (mxisd)
      set_fact:
        well_known_file_checks: "{{ well_known_file_checks + [well_known_file_check_matrix_server] }}"
  when: "matrix_well_known_matrix_server_enabled"

- name: Perform well-known checks
  include_tasks: "{{ role_path }}/tasks/self_check_well_known_file.yml"
  with_items: "{{ well_known_file_checks }}"
  loop_control:
    loop_var: well_known_file_check
