---

- name: Ensure Matrix Coturn path exists
  file:
    path: "{{ item.path }}"
    state: directory
    mode: 0750
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"
  with_items:
    - { path: "{{ matrix_coturn_docker_src_files_path }}", when: "{{ matrix_coturn_container_image_self_build }}"}
  when: "item.when|bool"

- name: Ensure Coturn image is pulled
  docker_image:
    name: "{{ matrix_coturn_docker_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ matrix_coturn_docker_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else matrix_coturn_docker_image_force_pull }}"
  when: "not matrix_coturn_container_image_self_build|bool"

- name: Ensure Coturn repository is present on self-build
  git:
    repo: "{{ matrix_coturn_container_image_self_build_repo }}"
    dest: "{{ matrix_coturn_docker_src_files_path }}"
    version: "{{ matrix_coturn_docker_image.split(':')[1] }}"
    force: "yes"
  register: matrix_coturn_git_pull_results
  when: "matrix_coturn_container_image_self_build|bool"

- name: Ensure Coturn Docker image is built
  docker_image:
    name: "{{ matrix_coturn_docker_image }}"
    source: build
    force_source: "{{ matrix_coturn_git_pull_results.changed }}"
    build:
      dockerfile: Dockerfile
      path: "{{ matrix_coturn_docker_src_files_path }}"
      pull: yes
  when: "matrix_coturn_container_image_self_build|bool"

- name: Ensure Coturn configuration path exists
  file:
    path: "{{ matrix_coturn_base_path }}"
    state: directory
    mode: 0750
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"

- name: Ensure turnserver.conf installed
  template:
    src: "{{ role_path }}/templates/turnserver.conf.j2"
    dest: "{{ matrix_coturn_config_path }}"
    mode: 0644

- name: Ensure Coturn network is created in Docker
  docker_network:
    name: "{{ matrix_coturn_docker_network }}"
    driver: bridge

- name: Ensure matrix-coturn.service installed
  template:
    src: "{{ role_path }}/templates/systemd/matrix-coturn.service.j2"
    dest: "{{ matrix_systemd_path }}/matrix-coturn.service"
    mode: 0644
  register: matrix_coturn_systemd_service_result

- name: Ensure systemd reloaded after matrix-coturn.service installation
  service:
    daemon_reload: yes
  when: "matrix_coturn_systemd_service_result.changed"

# This may be unnecessary when more long-lived certificates are used.
# We optimize for the common use-case though (short-lived Let's Encrypt certificates).
# Reloading doesn't hurt anyway, so there's no need to make this more flexible.
- name: Ensure periodic reloading of matrix-coturn is configured for SSL renewal (matrix-coturn-reload)
  template:
    src: "{{ role_path }}/templates/cron.d/matrix-coturn-ssl-reload.j2"
    dest: /etc/cron.d/matrix-coturn-ssl-reload
    mode: 0644
  when: "matrix_coturn_tls_enabled|bool"

# A similar task exists in `setup_uninstall.yml`
- name: Ensure matrix-coturn-ssl-reload cronjob removed
  file:
    path: /etc/cron.d/matrix-coturn-ssl-reload
    state: absent
  when: "not matrix_coturn_tls_enabled|bool"
