---

# A similar task exists in `setup_install.yml`
- name: Ensure matrix-coturn-ssl-reload cronjob removed
  file:
    path: /etc/cron.d/matrix-coturn-ssl-reload
    state: absent

- name: Check existence of matrix-coturn service
  stat:
    path: "{{ matrix_systemd_path }}/matrix-coturn.service"
  register: matrix_coturn_service_stat
  when: "not matrix_coturn_enabled|bool"

- name: Ensure matrix-coturn is stopped
  service:
    name: matrix-coturn
    state: stopped
    daemon_reload: yes
  register: stopping_result
  when: "not matrix_coturn_enabled|bool and matrix_coturn_service_stat.stat.exists"

- name: Ensure matrix-coturn.service doesn't exist
  file:
    path: "{{ matrix_systemd_path }}/matrix-coturn.service"
    state: absent
  when: "not matrix_coturn_enabled|bool and matrix_coturn_service_stat.stat.exists"

- name: Ensure systemd reloaded after matrix-coturn.service removal
  service:
    daemon_reload: yes
  when: "not matrix_coturn_enabled|bool and matrix_coturn_service_stat.stat.exists"

- name: Ensure Matrix coturn paths don't exist
  file:
    path: "{{ matrix_coturn_base_path }}"
    state: absent
  when: "not matrix_coturn_enabled|bool"

- name: Ensure coturn Docker image doesn't exist
  docker_image:
    name: "{{ matrix_coturn_docker_image }}"
    state: absent
  when: "not matrix_coturn_enabled|bool"
