matrix_mailer_enabled: true

matrix_mailer_base_path: "{{ matrix_base_data_path }}/mailer"

matrix_mailer_docker_image: "panubo/postfix:latest"

matrix_mailer_sender_address: "matrix@{{ hostname_identity }}"
matrix_mailer_relay_use: false
matrix_mailer_relay_host_name: "mail.example.com"
matrix_mailer_relay_host_port: 587
matrix_mailer_relay_auth: false
matrix_mailer_relay_auth_username: ""
matrix_mailer_relay_auth_password: ""