
- name: Check if matrix_vars.yml file exists
  stat:
    path: "/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml"
  register: matrix_vars_file

- name: Rename synapse presence variable
  delegate_to: 127.0.0.1
  replace:
    path: "/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml"
    regexp: 'matrix_synapse_use_presence'
    replace: 'matrix_synapse_presence_enabled'
  when: matrix_vars_file.stat.exists
