---

- name: Ensure Dimension base path exists
  file:
    path: "{{ matrix_dimension_base_path }}"
    state: directory
    mode: 0770
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_dimension_user_gid }}"

- name: Ensure Dimension config installed
  copy:
    content: "{{ matrix_dimension_configuration|to_nice_yaml }}"
    dest: "{{ matrix_dimension_base_path }}/config.yaml"
    mode: 0640
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_dimension_user_gid }}"

- name: Ensure Dimension image is pulled
  docker_image:
    name: "{{ matrix_dimension_docker_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ matrix_dimension_docker_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else matrix_dimension_docker_image_force_pull }}"

- name: Ensure matrix-dimension.service installed
  template:
    src: "{{ role_path }}/templates/systemd/matrix-dimension.service.j2"
    dest: "{{ matrix_systemd_path }}/matrix-dimension.service"
    mode: 0644
  register: matrix_dimension_systemd_service_result

- name: Ensure systemd reloaded after matrix-dimension.service installation
  service:
    daemon_reload: yes
  when: "matrix_dimension_systemd_service_result.changed|bool"
