---

- name: verify all necessary variables are present
  assert:
    that:
      - matrix_user_verification_service_uvs_access_token is defined and matrix_user_verification_service_uvs_access_token|length
      - matrix_user_verification_service_uvs_homeserver_url is defined and matrix_user_verification_service_uvs_homeserver_url|length
    fail_msg: "Missing variable in {{ matrix_user_verification_service_ansible_name }} role"
