---

- name: Ensure ddclient is installed
  pacman:
    name: ddclient
    state: latest
  when: "run_setup|bool and matrix_dynamic_dns_enabled|bool"

- name: Ensure ddclient is uninstalled
  pacman:
    name: ddclient
    state: absent
    update_cache: true
  become: true
  when: "run_setup|bool and not matrix_dynamic_dns_enabled|bool"
  