---

- name: Ensure yum packages are installed
  yum:
    name: epel-release
    state: latest
    update_cache: yes
  when: "run_setup|bool and matrix_dynamic_dns_enabled|bool"

- name: Ensure ddclient is installed
  yum:
    name: ddclient
    state: latest
  when: "run_setup|bool and matrix_dynamic_dns_enabled|bool"

- name: Ensure ddclient is uninstalled
  yum:
    name:
      - ddclient
      - epel-release
    state: absent
  when: "run_setup|bool and not matrix_dynamic_dns_enabled|bool"
