---

- name: Ensure ddclient domain config exists
  template:
    src: "{{ role_path }}/templates/ddclient.conf.j2"
    dest: "/etc/ddclient.conf"
    mode: 0600

- name: Ensure ddclient client config directory exists
  file:
    path: "/etc/default"
    state: directory
    mode: 0700
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"

- name: Ensure ddclient client config exists
  copy:
    content: "run_dhclient=\"true\"\nrun_ipup=\"false\"\nrun_daemon=\"false\""
    dest: "/etc/default/ddclient"
    mode: 0600
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"

- import_tasks: "{{ role_path }}/tasks/platform/main.yml"
