---

- name: Check existence of matrix-dynamic-dns service
  stat:
    path: "{{ systemd_path }}m/matrix-dynamic-dns.service"
  register: matrix_dynamic_dns_service_stat

- name: Ensure matrix-dynamic-dns is stopped
  service:
    name: matrix-dynamic-dns
    state: stopped
    daemon_reload: yes
  when: "matrix_dynamic_dns_service_stat.stat.exists"

- name: Ensure matrix-dynamic-dns.service doesn't exist
  file:
    path: "{{ systemd_path }}m/matrix-dynamic-dns.service"
    state: absent
  when: "matrix_dynamic_dns_service_stat.stat.exists"

- name: Ensure systemd reloaded after matrix-dynamic-dns.service removal
  service:
    daemon_reload: yes
  when: "matrix_dynamic_dns_service_stat.stat.exists"
