---

- name: Fail if required settings not defined in configuration blocks
  fail:
    msg: >-
      One of the configurations in matrix_dynamic_dns_domain_configurations is missing a required key (domain, provider, protocol).
  when: "'domain' not in configuration or 'provider' not in configuration or 'protocol' not in configuration"
  with_items: "{{ matrix_dynamic_dns_domain_configurations }}"
  loop_control:
    loop_var: configuration
