---

- when: matrix_synapse_admin_enabled | bool
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/inject_into_nginx_proxy.yml"
  tags:
    - setup-all
    - setup-nginx-proxy

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/validate_config.yml"
  when: run_setup | bool
  tags:
    - setup-all
    - setup-synapse-admin

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/setup.yml"
  tags:
    - setup-all
    - setup-synapse-admin
