---

- name: Fail if required settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == ''"
  with_items:
    - "matrix_mautrix_slack_appservice_token"
    - "matrix_mautrix_slack_homeserver_token"

- name: Fail if appservice-slack and mautrix-slack have conflicting bot usernames
  when: matrix_appservice_slack_enabled | default(False) | bool and matrix_mautrix_slack_appservice_bot_username == matrix_appservice_slack_bot_name | default ('')
  ansible.builtin.fail:
    msg: |
      The appservice-slack and mautrix-slack components are both enabled and use the same bot username ({{ matrix_mautrix_slack_appservice_bot_username }}), as per their default configuration, which causes a conflcit.
      To resolve the conflict, make one of these components use a different username.
      Consider either changing `matrix_mautrix_slack_appservice_bot_username` (the bot username for the mautrix-slack component) or `matrix_appservice_slack_bot_name` (the bot username for the appservice-slack component).
      We recommend that you change the username for the newly-added (and yet unused) component.
