---

# If the matrix-synapse role is not used, `matrix_synapse_role_executed` won't exist.
# We don't want to fail in such cases.
- name: Fail if matrix-synapse role already executed
  fail:
    msg: >-
      The matrix-bridge-mautrix-facebook role needs to execute before the matrix-synapse role.
  when: "matrix_synapse_role_executed|default(False)"

- name: Ensure Mautrix Facebook image is pulled
  docker_image:
    name: "{{ matrix_mautrix_facebook_docker_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"

- name: Ensure Mautrix Facebook paths exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_username }}"
  with_items:
    - "{{ matrix_mautrix_facebook_base_path }}"
    - "{{ matrix_mautrix_facebook_config_path }}"
    - "{{ matrix_mautrix_facebook_data_path }}"

- name: Check if an old database file already exists
  stat:
    path: "{{ matrix_mautrix_facebook_base_path }}/mautrix-facebook.db"
  register: matrix_mautrix_facebook_stat_database

- name: (Data relocation) Ensure matrix-mautrix-facebook.service is stopped
  service:
    name: matrix-mautrix-facebook
    state: stopped
    daemon_reload: yes
  failed_when: false
  when: "matrix_mautrix_facebook_stat_database.stat.exists"

- name: (Data relocation) Move mautrix-facebook database file to ./data directory
  command: "mv {{ matrix_mautrix_facebook_base_path }}/mautrix-facebook.db {{ matrix_mautrix_facebook_data_path }}/mautrix-facebook.db"
  when: "matrix_mautrix_facebook_stat_database.stat.exists"

- name: Ensure mautrix-facebook config.yaml installed
  copy:
    content: "{{ matrix_mautrix_facebook_configuration|to_nice_yaml }}"
    dest: "{{ matrix_mautrix_facebook_config_path }}/config.yaml"
    mode: 0644
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_username }}"

- name: Ensure mautrix-facebook registration.yaml installed
  copy:
    content: "{{ matrix_mautrix_facebook_registration|to_nice_yaml }}"
    dest: "{{ matrix_mautrix_facebook_config_path }}/registration.yaml"
    mode: 0644
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_username }}"

- name: Ensure matrix-mautrix-facebook.service installed
  template:
    src: "{{ role_path }}/templates/systemd/matrix-mautrix-facebook.service.j2"
    dest: "/etc/systemd/system/matrix-mautrix-facebook.service"
    mode: 0644
  register: matrix_mautrix_facebook_systemd_service_result

- name: Ensure systemd reloaded after matrix-mautrix-facebook.service installation
  service:
    daemon_reload: yes
  when: "matrix_mautrix_facebook_systemd_service_result.changed"

# If the matrix-synapse role is not used, these variables may not exist.
- set_fact:
    matrix_synapse_container_extra_arguments: >
      {{ matrix_synapse_container_extra_arguments|default([]) }}
      +
      {{ ["--mount type=bind,src={{ matrix_mautrix_facebook_config_path }}/registration.yaml,dst=/matrix-mautrix-facebook-registration.yaml,ro"] }}

    matrix_synapse_app_service_config_files: >
      {{ matrix_synapse_app_service_config_files|default([]) }}
      +
      {{ ["/matrix-mautrix-facebook-registration.yaml"] }}
