---

- name: Ensure hookshot image is pulled
  docker_image:
    name: "{{ matrix_hookshot_docker_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ matrix_hookshot_docker_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else matrix_hookshot_docker_image_force_pull }}"

- name: Ensure hookshot paths exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"
  with_items:
    - "{{ matrix_hookshot_base_path }}"

# - name: Ensure openssl is installed (#1510)

- name: Check if hookshot passkey exists
  stat:
    path: "{{ matrix_hookshot_data_path }}/passkey.pem"
  register: hookshot_passkey_file

- name: Generate hookshot passkey if it doesn't exist
  shell: "{{ matrix_host_command_openssl }} genpkey -out {{ matrix_hookshot_base_path }}/passkey.pem -outform PEM -algorithm RSA -pkeyopt rsa_keygen_bits:4096"
  become: true
  become_user: "{{ matrix_user_username }}"
  when: "not hookshot_passkey_file.stat.exists"

- name: Ensure hookshot config.yaml installed if provided
  copy:
    content: "{{ matrix_hookshot_config|to_nice_yaml }}"
    dest: "{{ matrix_hookshot_base_path }}/config.yaml"
    mode: 0644
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"

- name: Ensure hookshot registration.yaml installed if provided
  copy:
    content: "{{ matrix_hookshot_registration|to_nice_yaml }}"
    dest: "{{ matrix_hookshot_base_path }}/registration.yaml"
    mode: 0644
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"

- name: Ensure matrix-hookshot.service installed
  template:
    src: "{{ role_path }}/templates/systemd/matrix-hookshot.service.j2"
    dest: "{{ matrix_systemd_path }}/matrix-hookshot.service"
    mode: 0644
  register: matrix_hookshot_systemd_service_result

- name: Ensure systemd reloaded after matrix-hookshot.service installation
  service:
    daemon_reload: yes
  when: matrix_hookshot_systemd_service_result.changed
