---

- name: Ensure Matrix services stopped
  ansible.builtin.service:
    name: "{{ item.name }}"
    state: stopped
  with_items: "{{ matrix_systemd_services_list | sort (attribute='priority,name', reverse=true) }}"
