---

- name: Fail if required settings not defined
  fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == ''"
  with_items:
    - "matrix_mautrix_telegram_api_id"
    - "matrix_mautrix_telegram_api_hash"
    - "matrix_mautrix_telegram_public_endpoint"
