---

- import_tasks: tasks/setup/setup_sanity_check.yml
  tags:
    - always

- import_tasks: tasks/setup/setup_base.yml
  tags:
    - setup-all

- import_tasks: tasks/setup/setup_main.yml
  tags:
    - setup-all

- import_tasks: tasks/setup/ssl/main.yml
  tags:
    - setup-all
    - setup-ssl

- import_tasks: tasks/setup/setup_postgres.yml
  tags:
    - setup-all
    - setup-postgres

- import_tasks: tasks/setup/setup_goofys.yml
  tags:
    - setup-all
    - setup-goofys

- import_tasks: tasks/setup/setup_coturn.yml
  tags:
    - setup-all
    - setup-coturn

- import_tasks: tasks/setup/setup_mailer.yml
  tags:
    - setup-all
    - setup-mailer

- import_tasks: tasks/setup/setup_mxisd.yml
  tags:
    - setup-all
    - setup-mxisd

- import_tasks: tasks/setup/setup_corporal_overrides.yml
  tags:
    - always

- import_tasks: tasks/setup/setup_corporal.yml
  tags:
    - setup-all
    - setup-corporal

- import_tasks: tasks/setup/synapse/main.yml
  tags:
    - setup-all
    - setup-synapse
    - setup-coturn

- import_tasks: tasks/setup/setup_riot_web.yml
  tags:
    - setup-all
    - setup-riot-web

- import_tasks: tasks/setup/setup_well_known.yml
  tags:
    - setup-all
    - setup-mxisd
    - setup-synapse
    - setup-nginx-proxy
    - setup-well-known

- import_tasks: tasks/setup/setup_nginx_proxy.yml
  tags:
    - setup-all
    - setup-nginx-proxy
    - setup-well-known