---

- include: tasks/setup/setup_base.yml
  tags:
    - setup-all

- include: tasks/setup/setup_main.yml
  tags:
    - setup-all

- include: tasks/setup/ssl/main.yml
  tags:
    - setup-all
    - setup-ssl

- include: tasks/setup/setup_postgres.yml
  tags:
    - setup-all
    - setup-postgres

- include: tasks/setup/setup_goofys.yml
  tags:
    - setup-all
    - setup-goofys

- include: tasks/setup/setup_coturn.yml
  tags:
    - setup-all
    - setup-coturn

- include: tasks/setup/setup_mailer.yml
  tags:
    - setup-all
    - setup-mailer

- include: tasks/setup/setup_mxisd.yml
  tags:
    - setup-all
    - setup-mxisd

- include: tasks/setup/setup_corporal_overrides.yml
  tags:
    - always

- include: tasks/setup/setup_corporal.yml
  tags:
    - setup-all
    - setup-corporal

- include: tasks/setup/synapse/main.yml
  tags:
    - setup-all
    - setup-synapse
    - setup-coturn

- include: tasks/setup/setup_riot_web.yml
  tags:
    - setup-all
    - setup-riot-web

- include: tasks/setup/setup_well_known.yml
  tags:
    - setup-all
    - setup-mxisd
    - setup-synapse
    - setup-nginx-proxy
    - setup-well-known

- include: tasks/setup/setup_nginx_proxy.yml
  tags:
    - setup-all
    - setup-nginx-proxy
    - setup-well-known