---

- name: Fail if Macaroon key is missing
  fail:
    msg: "You need to set a secret in the matrix_synapse_macaroon_secret_key variable"
  when: "matrix_synapse_macaroon_secret_key == ''"

- name: Fail if Coturn Auth secret is missing
  fail:
    msg: "You need to set a secret in the matrix_coturn_turn_static_auth_secret variable"
  when: "matrix_coturn_turn_static_auth_secret == ''"