---

#
# Tasks related to setting up the mailer
#

- name: Ensure mailer environment variables file created
  template:
    src: "{{ role_path }}/templates/env/{{ item }}.j2"
    dest: "{{ matrix_environment_variables_data_path }}/{{ item }}"
    mode: 0640
  with_items:
    - "env-mailer"

- name: Ensure mailer image is pulled
  docker_image:
    name: "{{ matrix_mailer_docker_image }}"
  when: matrix_mailer_enabled

- name: Ensure matrix-mailer.service installed
  template:
    src: "{{ role_path }}/templates/systemd/matrix-mailer.service.j2"
    dest: "/etc/systemd/system/matrix-mailer.service"
    mode: 0644
  when: matrix_mailer_enabled

#
# Tasks related to getting rid of the mailer (if it was previously enabled)
#

- name: Check existence of matrix-mailer service
  stat: path="/etc/systemd/system/matrix-mailer.service"
  register: matrix_mailer_service_stat

- name: Ensure matrix-mailer is stopped
  service: name=matrix-mailer state=stopped daemon_reload=yes
  register: stopping_result
  when: "not matrix_mailer_enabled and matrix_mailer_service_stat.stat.exists"

- name: Ensure matrix-mailer.service doesn't exist
  file:
    path: "/etc/systemd/system/matrix-mailer.service"
    state: absent
  when: "not matrix_mailer_enabled and matrix_mailer_service_stat.stat.exists"

- name: Ensure Matrix mailer environment variables path doesn't exist
  file:
    path: "{{ matrix_environment_variables_data_path }}/env-mailer"
    state: absent
  when: "not matrix_mailer_enabled"

- name: Ensure mailer Docker image doesn't exist
  docker_image:
    name: "{{ matrix_mailer_docker_image }}"
    state: absent
  when: "not matrix_mailer_enabled"