---

- include: tasks/setup/setup_synapse_ext_rest_auth.yml

- include: tasks/setup/setup_synapse_ext_shared_secret_auth.yml

- include: tasks/setup/setup_synapse_ext_ldap.yml

- include: tasks/setup/setup_synapse_ext_mautrix_telegram.yml

- include: tasks/setup/setup_synapse_ext_mautrix_whatsapp.yml
