---

#
# Tasks related to setting up riot-web
#

- name: Ensure Matrix riot-web path exists
  file:
    path: "{{ matrix_riot_web_data_path }}"
    state: directory
    mode: 0750
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_username }}"
  when: matrix_riot_web_enabled

- name: Ensure riot-web Docker image is pulled
  docker_image:
    name: "{{ matrix_riot_web_docker_image }}"
  when: matrix_riot_web_enabled

- name: Ensure Matrix riot-web configured
  template:
    src: "{{ item.src }}"
    dest: "{{ matrix_riot_web_data_path }}/{{ item.name }}"
    mode: 0644
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_username }}"
  with_items:
    - {src: "{{ role_path }}/templates/riot-web/riot.im.conf.j2", name: "riot.im.conf"}
    - {src: "{{ role_path }}/templates/riot-web/config.json.j2", name: "config.json"}
    - {src: "{{ matrix_riot_web_homepage_template }}", name: "home.html"}
  when: matrix_riot_web_enabled

- name: Ensure matrix-riot-web.service installed
  template:
    src: "{{ role_path }}/templates/systemd/matrix-riot-web.service.j2"
    dest: "/etc/systemd/system/matrix-riot-web.service"
    mode: 0644
  when: matrix_riot_web_enabled

#
# Tasks related to getting rid of riot-web (if it was previously enabled)
#

- name: Check existence of matrix-riot-web service
  stat:
    path: "/etc/systemd/system/matrix-riot-web.service"
  register: matrix_riot_web_service_stat

- name: Ensure matrix-riot-web is stopped
  service:
    name: matrix-riot-web
    state: stopped
    daemon_reload: yes
  register: stopping_result
  when: "not matrix_riot_web_enabled and matrix_riot_web_service_stat.stat.exists"

- name: Ensure matrix-riot-web.service doesn't exist
  file:
    path: "/etc/systemd/system/matrix-riot-web.service"
    state: absent
  when: "not matrix_riot_web_enabled and matrix_riot_web_service_stat.stat.exists"

- name: Ensure Matrix riot-web paths doesn't exist
  file:
    path: "{{ matrix_riot_web_data_path }}"
    state: absent
  when: "not matrix_riot_web_enabled"

- name: Ensure riot-web Docker image doesn't exist
  docker_image:
    name: "{{ matrix_riot_web_docker_image }}"
    state: absent
  when: "not matrix_riot_web_enabled"
