- set_fact:
    matrix_systemd_services_list: "{{ matrix_systemd_services_list + ['matrix-synapse'] }}"
  when: matrix_synapse_enabled|bool

- set_fact:
    matrix_systemd_services_list: "{{ matrix_systemd_services_list + ['matrix-goofys'] }}"
  when: matrix_s3_media_store_enabled|bool
