---

- set_fact:
    matrix_client_api_url_endpoint_public: "https://{{ hostname_matrix }}/_matrix/client/versions"

- name: Check Matrix Client API
  uri:
    url: "{{ matrix_client_api_url_endpoint_public }}"
    follow_redirects: false
  register: result_matrix_client_api
  ignore_errors: true

- name: Fail if Matrix Client API not working
  fail:
    msg: "Failed checking Matrix Client API is up at `{{ hostname_matrix }}` (checked endpoint: `{{ matrix_client_api_url_endpoint_public }}`). Is Synapse running? Is port 443 open in your firewall? Full error: {{ result_matrix_client_api }}"
  when: "result_matrix_client_api.failed or 'json' not in result_matrix_client_api"

- name: Report working Matrix Client API
  debug:
    msg: "The Matrix Client API at `{{ hostname_matrix }}` (checked endpoint: `{{ matrix_client_api_url_endpoint_public }}`) is working"