---

- name: Fail if required Synapse settings not defined
  fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`) for using Synapse.
  when: "vars[item] == ''"
  with_items:
    - "matrix_synapse_macaroon_secret_key"