---

- block:
    - when: matrix_s3_media_store_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/goofys/setup_install.yml"

    - when: not matrix_s3_media_store_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/goofys/setup_uninstall.yml"
  tags:
    - setup-all
    - setup-synapse
