---
- name: Fail if required Cinny settings not defined
  fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`) to use Cinny.
  when: "(vars[item] == '' or vars[item] is none) and matrix_client_cinny_container_image_self_build|bool"
  with_items:
    - "matrix_client_cinny_default_hs_url"
