---

- name: Retrieve IP of postgres container
  shell: "docker inspect matrix-postgres | jq -r '.[0].NetworkSettings.Networks.{{ matrix_docker_network }}.IPAddress'"
  register: matrix_postgres_container_ip

- name: Create additional users in postgres
  postgresql_user:
    name: "{{ item.username }}"
    password: "{{ item.pass }}"
    login_host: "{{ matrix_postgres_container_ip.stdout }}"
    login_port: 5432
    login_user: "{{ matrix_postgres_connection_username }}"
    login_password: "{{ matrix_postgres_connection_password }}"
    login_db: "{{ matrix_postgres_db_name }}"
  loop: matrix_postgres_additional_databases

- name: Create additional users in postgres
  postgresql_db:
    name: "{{ item.name }}"
    owner: "{{ item.username }}"
    lc_ctype: 'C'
    lc_collate: 'C'
    login_host: "{{ matrix_postgres_container_ip.stdout }}"
    login_port: 5432
    login_user: "{{ matrix_postgres_connection_username }}"
    login_password: "{{ matrix_postgres_connection_password }}"
  loop: matrix_postgres_additional_databases
