---

# TODO - we should ensure matrix-postgres.service is started.
# .. and that if we had just started it, we've given it ample time to initialize,
# before we attempt to run queries against it.

- name: Create additional Postgers user and database
  include_tasks: "{{ role_path }}/tasks/util/create_additional_database.yml"
  with_items: "{{ matrix_postgres_additional_databases }}"
  loop_control:
    loop_var: additional_db
  # Suppress logging to avoid dumping the credentials to the shell
  no_log: true
