---

- name: Fail if docker image not availble for arch
  ansible.builtin.fail:
    msg: >
      'prometheus-nginxlog-exporter' docker image is not available for your arch '{{ matrix_architecture }}'.

      We currently do not support building an image using this playbook.

      You can use a custom-build image by setting
          'matrix_prometheus_nginxlog_exporter_docker_image_arch_check_enabled: false'
          'matrix_prometheus_nginxlog_exporter_docker_image: path/to/docker/image:tag'

      or disable 'prometheus-nginxlog-exporter' by setting
          'matrix_prometheus_nginxlog_exporter: false'

      in vars.yml
  when: matrix_prometheus_nginxlog_exporter_docker_image_arch_check_enabled and matrix_architecture not in matrix_prometheus_nginxlog_exporter_docker_image_arch
