---

- import_tasks: tasks/setup/main.yml
  when: run_setup

- import_tasks: tasks/import/import_postgres.yml
  tags:
    - import-postgres
  when: run_import_postgres

- import_tasks: tasks/upgrade_postgres.yml
  tags:
    - upgrade-postgres
  when: run_upgrade_postgres

- import_tasks: tasks/start.yml
  tags:
    - start
  when: run_start

- import_tasks: tasks/register_user.yml
  tags:
    - register-user
  when: run_register_user

- import_tasks: tasks/import/import_sqlite_db.yml
  tags:
    - import-sqlite-db
  when: run_import_sqlite_db

- import_tasks: tasks/import/import_media_store.yml
  tags:
    - import-media-store
  when: run_import_media_store

- import_tasks: tasks/self_check/main.yml
  delegate_to: 127.0.0.1
  become: false
  tags:
    - self-check
  when: run_self_check
