---

- import_tasks: tasks/setup/synapse/ext/setup_synapse_ext_rest_auth.yml

- import_tasks: tasks/setup/synapse/ext/setup_synapse_ext_shared_secret_auth.yml

- import_tasks: tasks/setup/synapse/ext/setup_synapse_ext_ldap_auth.yml

- import_tasks: tasks/setup/synapse/ext/setup_synapse_ext_mautrix_telegram.yml

- import_tasks: tasks/setup/synapse/ext/setup_synapse_ext_mautrix_whatsapp.yml
