---

- block:
    - when: matrix_client_hydrogen_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: matrix_client_hydrogen_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_install.yml"

    - when: not matrix_client_hydrogen_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_uninstall.yml"
  tags:
    - setup-all
    - setup-client-hydrogen

- block:
    - when: matrix_client_hydrogen_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/self_check.yml"
  tags:
    - self-check
