---
# a negative when condition will not actually prevent ansible from executing loops in imported tasks!

- import_tasks: "{{ role_path }}/tasks/workers/setup_install.yml"
  when: "matrix_synapse_enabled|bool and matrix_synapse_workers_enabled|bool"

- import_tasks: "{{ role_path }}/tasks/workers/setup_uninstall.yml"
  when: "not matrix_synapse_workers_enabled|bool"
