---

- name: Find worker configs to be cleaned
  find:
    path: "{{ matrix_synapse_config_dir_path }}"
    patterns: "worker.*.yaml"
    use_regex: true
  register: matrix_synapse_workers_current_config_files

- name: Ensure previous worker configs are cleaned
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ matrix_synapse_workers_current_config_files.files }}"

- name: Find worker systemd services to be cleaned
  find:
    path: "{{ matrix_systemd_path }}"
    patterns: "matrix-synapse-worker.*.service"
    use_regex: true
  register: matrix_synapse_workers_current_systemd_services

- name: Ensure previous worker systemd services are cleaned
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ matrix_synapse_workers_current_systemd_services.files }}"

- name: Ensure creation of worker systemd service files and configuration files
  include_tasks: "{{ role_path }}/tasks/workers/util/setup_files_for_worker.yml"
  with_items: "{{ matrix_synapse_workers_enabled_list }}"
  loop_control:
    loop_var: matrix_synapse_worker_details
