---

- ansible.builtin.set_fact:
    matrix_systemd_services_list: "{{ matrix_systemd_services_list + ['matrix-synapse-reverse-proxy-companion.service'] }}"
  when: matrix_synapse_reverse_proxy_companion_enabled | bool
