---

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/init.yml"
  tags:
    - always

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/setup_install.yml"
  when: run_setup | bool and matrix_synapse_reverse_proxy_companion_enabled | bool
  tags:
    - setup-all
    - setup-synapse-reverse-proxy-companion
    - setup-synapse

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/setup_uninstall.yml"
  when: run_setup | bool and not matrix_synapse_reverse_proxy_companion_enabled | bool
  tags:
    - setup-all
    - setup-synapse-reverse-proxy-companion
    - setup-synapse
