---

- name: Ensure systemd reloaded
  service:
    daemon_reload: yes

- name: Ensure Matrix services stopped
  service:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ matrix_systemd_services_list }}"

- name: Ensure Matrix services started
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ matrix_systemd_services_list }}"