- name: Fail if no Sygnal apps defined
  fail:
    msg: >-
      Enabling Sygnal requires that you specify at least one app in `matrix_sygnal_apps`
  with_items:
    - "matrix_sygnal_access_token"
  when: "matrix_sygnal_enabled and matrix_sygnal_apps|length == 0"
